vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        avatar_file:
            uri_prefix: /upload/images/avatar
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

